# Sherlock Intelligence Workstation
# Rainy London × Brass Archives × Tokyo Night Foundation
# Optimized for Development, OSINT, RE and Research

foreground #d6d2c4
background #171b24

# Black
color0 #384154
color8 #475166

# Red
color1 #a55d68
color9 #b86d78

# Green
color2 #7d9571
color10 #8da583

# Yellow
color3 #b08d57
color11 #c9b68d

# Blue
color4 #7c92b3
color12 #8fa4c2

# Magenta
color5 #9a8db5
color13 #b0a2ca

# Cyan
color6 #6f8f8f
color14 #84a5a5

# White
color7 #d6d2c4
color15 #e5dfd1

# Cursor
cursor #c9b68d
cursor_text_color #171b24

# Selection highlight
selection_foreground none
selection_background #2b3243

# The color for highlighting URLs on mouse-over
url_color #7d9571

# Window borders
active_border_color #b08d57
inactive_border_color #11141b
bell_border_color #c9b68d

# Tab bar
# tab_bar_style fade
# tab_fade 1
active_tab_foreground   #171b24
active_tab_background   #b08d57
active_tab_font_style   bold
inactive_tab_foreground #9f998d
inactive_tab_background #171b24
inactive_tab_font_style bold
tab_bar_background #11141b
#
# Title bar
macos_titlebar_color #171b24

# Storm
background #1d2230
cursor_text_color #1d2230
active_tab_background   #2b3243
inactive_tab_background #2b3243
macos_titlebar_color #2b3243
